# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "host0" => "192.168.33.10"
}

Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 80, host: 8081

  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "ubuntu/xenial64"
      machine.vm.hostname = "%s.dev.starthack.it" % name
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
          v.name = name
          v.customize ["modifyvm", :id, "--memory", 1500]
      end

      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "setup.yml"
        ansible.compatibility_mode = '2.0'
        ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
      end
    end
  end
end
