INSERT INTO users (
        user_id,
        email,
        username,
        password_hash,
        user_type
    )
VALUES (
        'user-test-1234567890',
        'test@mail.com',
        'test-user',
        '$2a$10$f3U9QBJ.iBmUIoIQTHl6.ep7xMcufE2lh/uBPoYGkbszloEfIAxhW',
        'basic'
    ),
    (
        'alice-1234567890',
        'alice@mail.com',
        'alice',
        '$2a$10$f3U9QBJ.iBmUIoIQTHl6.ep7xMcufE2lh/uBPoYGkbszloEfIAxhW',
        'basic'
    ),
    (
        'admin-1234567890',
        'admin@mail.com',
        'admin',
        '$2a$10$f3U9QBJ.iBmUIoIQTHl6.ep7xMcufE2lh/uBPoYGkbszloEfIAxhW',
        'admin'
    ),
    (
        'bob-1234567890',
        'bob@mail.com',
        'bob',
        '$2a$10$f3U9QBJ.iBmUIoIQTHl6.ep7xMcufE2lh/uBPoYGkbszloEfIAxhW',
        'admin'
    );