from: node:8
services:
  - rabbitmq:
      from: gonkulatorlabs/rabbitmq
      expose:
        - 5672:5672
  - postgres:
      from: kiasaki/alpine-postgres
      env:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=dev
      expose:
        - 5432:5432
  - redis:
      from: smebberson/alpine-redis
      expose:
        - "6379"
expose:
  - 9000:9000
quiet: false
forward: true
tasks:
  env: env | sort && sleep 300000
  clean: npm run clean
  install: env
  test: npm run test
  lint: npm run lint
  build: npm run build
  start: npm start
  ci: .lint .test .build
