@startmindmap
title Resources for project grucloud-aws
skinparam monochrome true
+ Infra
++ aws
+++ ec2
++++ KeyPair (1)
+++++ grucloud-app
++++ Vpc (1)
+++++ vpc
++++ InternetGateway (1)
+++++ ig
++++ Subnet (1)
+++++ subnet
++++ RouteTable (1)
+++++ route-table
++++ Route (1)
+++++ route-ig
++++ SecurityGroup (1)
+++++ securityGroup
++++ SecurityGroupRuleIngress (4)
+++++ sg-rule-ingress-ssh
+++++ sg-rule-ingress-http
+++++ sg-rule-ingress-https
+++++ sg-rule-ingress-icmp
++++ ElasticIpAddress (1)
+++++ ip
++++ Image (1)
+++++ ubuntu 20.04
++++ Volume (1)
+++++ volume
++++ Instance (1)
+++++ server
+++ route53Domain
++++ Domain (1)
+++++ grucloud.com
+++ route53
++++ HostedZone (1)
+++++ grucloud.com.
++++ Record (4)
+++++ app.grucloud.com.
+++++ grucloud.com.
+++++ grucloud.com.-gitpage-record-www
+++++ grucloud.com.-mx
@endmindmap