#%RAML 0.8
---
title: Starhackit
baseUri: http://localhost:8080/api/v1
version: v1
mediaType: application/json
protocols: [ HTTP, HTTPS ]
documentation:
 - title: Job REST API
   content: 'Job REST API documentation'

traits: !include traits.raml

/job:
  description: Create, Read, Update and Delete a job
  get:
    is: [
      searchable: {description: "with valid searchable fields: title", example: "[\"title\", \"DevOps\", \"like\"]"},
      orderable: {fieldsList: "title"},
      pageable
    ]
    responses:
      200:
        body:
          example: !include jobs.out.sample.json

  post:
    description: Create a job 
    body:
      application/json:
        example: !include job.in.sample.json
    responses:
      200:
        body:
          example: !include job.out.sample.json
        
  /{id}:
    description: Get one job
    get:
      responses:
        200:
          body:
            example: !include job.out.sample.json

    delete:
      responses:
        204:
    patch:
      body:
        application/json:
          example: !include job.in.sample.json
      responses:
        200:
          body:
            example: !include job.out.sample.json
