export default () => ({
  features: [
    {
      icon: 'icon-stackexchange',
      title: 'Full Stack',
      text: 'A complete frontend, backend and deployment solution to bootstrap your application',
    },
    {
      icon: 'icon-user',
      title: 'Authentication',
      text: 'Account registration with username and password, or with identity provider such as Google, Facebook, Twitter, GitHub etc ..',
    },
    {
      icon: 'icon-shield',
      title: 'Authorization',
      text: 'A group and permissions based authorization',
    },
    {
      icon: 'icon-database',
      title: 'Relational SQL Database',
      text: 'The data are modeled with sequelize, an ORM which support PostgreSQL, MySQL, MariaDB, SQLite and MSSQL',
    },
  ],
  frontend: [
    {
      img: 'assets/img/react.svg',
      height: '200',
      title: 'React',
      link: 'https://facebook.github.io/react/',
      text: 'A fast rising javascript library for building user interface.',
    },
    {
      img: 'assets/img/material-ui.svg',
      title: 'Material-UI',
      height: '200',
      link: 'http://www.material-ui.com',
      text: "A Set of React Components that Implement Google's Material Design.",
    },
    {
      img: 'assets/img/redux.png',
      title: 'Redux',
      height: '200',
      link: 'https://github.com/reactjs/redux',
      text: 'Predictable state container, the most popular flux library.',
    },
  ],
  backend: [
    {
      img: 'assets/img/nodejs.png',
      title: 'Node.js',
      height: '120',
      link: 'https://nodejs.org',
      text: 'A scalable javascript application server.',
    },
    {
      img: 'assets/img/sequelize.png',
      height: '120',
      title: 'Sequelize',
      link: 'http://docs.sequelizejs.com/en/latest/',
      text: 'Sequelize is a promise-based ORM for Node.js and io.js. It supports the dialects PostgreSQL, MySQL, MariaDB, SQLite and MSSQL',
    },
    {
      img: 'assets/img/rabbitmq.png',
      title: 'RabbitMq',
      width: '200',
      link: 'assets/img/rabbitmq.png',
      text: 'Robust messaging for applications',
    },
    {
      img: 'assets/img/passportjs.png',
      title: 'Passportjs',
      width: '64',
      link: 'http://passportjs.org/',
      text: 'Simple, unobtrusive authentication for Node.js, supports more than 300 authentication stragegies such as username and password, Facebook, google etc ...',
    },
  ],
  tools: [
    {
      img: 'assets/img/webpack.png',
      title: 'Webpack',
      height: '160',
      link: 'http://webpack.github.io/docs/',
      text: 'A bundler for javascript and friends. Packs many modules into a few bundled assets.',
    },
    {
      img: 'assets/img/nodemon.svg',
      title: 'Nodemon',
      height: '160',
      link: 'http://nodemon.io/',
      text: 'Monitors for any changes in your node.js application and automatically restart the server',
    },
    {
      img: 'assets/img/travis.png',
      title: 'Travis CI',
      height: '160',
      link: 'https://travis-ci.org/',
      text: 'A continuous integration platform.',
    },
    {
      img: 'assets/img/codeclimate.png',
      title: 'CodeClimate',
      height: '200',
      link: 'https://codeclimate.com/',
      text: 'Code Coverage and Code Review',
    },
    {
      img: 'assets/img/raml.png',
      title: 'RAML',
      link: 'http://raml.org',
      text: 'RESTful API Modeling Language, model your API, generate html documentation, mock server for frontend, ensure the backend implements the API',
    },
    {
      img: 'assets/img/pm2.png',
      title: 'PM2',
      width: '200',
      link: 'http://pm2.keymetrics.io/',
      text: 'Advanced, production process manager for Node.js',
    },
    {
      img: 'assets/img/ansible.png',
      title: 'Ansible',
      width: '128',
      link: 'http://www.ansible.com/',
      text: 'Deploy apps. Manage systems. DevOps made easy',
    },
    {
      img: 'assets/img/vagrant.png',
      title: 'Vagrant',
      link: 'https://www.vagrantup.com/',
      text: 'Create and configure lightweight, reproducible, and portable development environments.',
    },
    {
      img: 'assets/img/docker.png',
      title: 'Docker',
      link: 'https://www.docker.com/',
      text: 'An open platform for distributed applications for developers and sysadmins',
    },
  ],
});
