---
- name: Copy api.json config
  template:
    src: api.json.j2
    dest: /home/{{user}}/api.json
    owner: "{{user}}"
    mode: "0600"

- name: docker run api
  docker_container:
    name: api
    pull: yes
    image: "{{ api_image }}:{{ api_tag }}"
    state: started
    recreate: yes
    restart_policy: "always"
    volumes:
      - /home/{{user}}/api.json:/app/config/production.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/{{user}}/output:/app/output
      - /home/{{user}}/input:/app/input

    published_ports:
      - "9000:9000"
    env:
      NODE_ENV: "production"
      S3_AWS_REGION: "{{S3_AWS_REGION}}"
      S3_AWSAccessKeyId: "{{S3_AWSAccessKeyId}}"
      S3_AWSSecretKey: "{{S3_AWSSecretKey}}"
      OAUTH2_CLIENT_SECRET: "{{OAUTH2_CLIENT_SECRET}}"

    networks:
      - name: net
  tags:
    - containers
    - app
